---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure multipath-tools is installed on Debian.
  apt: "name={{ multipath_packages }} state={{ multipath_packages_state }}"
